name: 'Studio Client .NET Test'
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Run Tests
        env:
          SKYLAB_API_TOKEN: ${{ secrets.SKYLAB_API_TOKEN }}
          SKYLAB_API_URL: ${{ secrets.SKYLAB_API_URL }}
        run: dotnet test StudioClient.Tests

  notify:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test]

    steps:
      - name: Notify Slack
        uses: skylab-tech/github-actions-slack-notifier@v1
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
